myapp:
  build: .
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ..:/var/www/html/myapp
  links:
    - mysql

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: myapp
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
