web:
  build: .
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ..:/var/www/html
  links:
    - mysql

mysql:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_DATABASE: webapp
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
